name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload-artifacts: true

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: audio-controller-*
          path: ./release-files
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          files: ./release-files/*
          draft: false
          prerelease: false
